//
//  ActivityAnimationView.h
//  Activity
//
//  Created by Venkata Maniteja on 2015-12-11.
//  Copyright (c) 2015 Teja Nandamuri. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface ActivityAnimationView : NSObject

// Drawing Methods
+ (void)drawActivityWithMoveLevel: (CGFloat)moveLevel exersizeLevel: (CGFloat)exersizeLevel standLevel: (CGFloat)standLevel;
+ (void)drawActivityCompositionWithMoveLevel: (CGFloat)moveLevel exersizeLevel: (CGFloat)exersizeLevel standLevel: (CGFloat)standLevel;
+ (void)drawCanvas1;

// Generated Images
+ (UIImage*)imageOfActivityCompositionWithMoveLevel: (CGFloat)moveLevel exersizeLevel: (CGFloat)exersizeLevel standLevel: (CGFloat)standLevel;

@end
